controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


forward_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
      - joint3
    interface_name: position

padman_controller:
  ros__parameters:
    type: padman_controller/PadmanController
    joints:
      - joint1
      - joint2
      - joint3
    state_joints:
      - joint1
      - joint2
      - joint3
    interface_name: effort

    
