controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


forward_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1_l
      - joint2_l
      - joint3_l
      - joint1_r
      - joint2_r
      - joint3_r
    interface_name: position

forward_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1_l
      - joint2_l
      - joint3_l
      - joint1_r
      - joint2_r
      - joint3_r
    interface_name: effort

padman_controller:
  ros__parameters:
    type: padman_controller/PadmanController
    joints:
      - joint1_l
      - joint2_l
      - joint3_l
      - joint1_r
      - joint2_r
      - joint3_r
    state_joints:
      - joint1_l
      - joint2_l
      - joint3_l
      - joint1_r
      - joint2_r
      - joint3_r
    interface_name: effort


    
